name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.172.233.187 << 'EOF'
            cd ~/flask-app-2
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
